blank_issues_enabled: false
contact_links:
  - name: ☎️ Veuillez nous rejoindre sur Discord, pour toutes questions ou demandes !
    url: https://discord.com/invite/DphdquZv
    about: Veuillez ne pas ouvrir d'issue autre que pour signaler des bugs ou demander de l'aide.
