services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - backend-net

  backend-update-server:
    image: btherin/valkream-update-server:latest
    container_name: backend-update-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - ./.env # Chemin relatif vers votre .env custom
    # Ajoute ici d'autres variables d'environnement si besoin
    networks:
      - backend-net

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60

networks:
  backend-net:
    driver: bridge
